// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFClient;

namespace WPFClient.Migrations
{
    [DbContext(typeof(StorageContext))]
    partial class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WPFClient.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResultId");

                    b.HasIndex("ResultDataId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("WPFClient.ResultData", b =>
                {
                    b.Property<int>("ResultDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("file")
                        .HasColumnType("BLOB");

                    b.HasKey("ResultDataId");

                    b.ToTable("ResultsData");
                });

            modelBuilder.Entity("WPFClient.Result", b =>
                {
                    b.HasOne("WPFClient.ResultData", "resultData")
                        .WithMany()
                        .HasForeignKey("ResultDataId");

                    b.Navigation("resultData");
                });
#pragma warning restore 612, 618
        }
    }
}
