// <auto-generated />
using System;
using ASPServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPServer.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20201201165026_FirstVersion")]
    partial class FirstVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ASPServer.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResultId");

                    b.HasIndex("ResultDataId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("ASPServer.ResultData", b =>
                {
                    b.Property<int>("ResultDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("file")
                        .HasColumnType("BLOB");

                    b.HasKey("ResultDataId");

                    b.ToTable("ResultData");
                });

            modelBuilder.Entity("ASPServer.Result", b =>
                {
                    b.HasOne("ASPServer.ResultData", "resultData")
                        .WithMany()
                        .HasForeignKey("ResultDataId");

                    b.Navigation("resultData");
                });
#pragma warning restore 612, 618
        }
    }
}
